[tool.poetry]
name = "cvapianalyser"
version = "1.43.5"
description = "plugin tool for capturing API coverage with input of a SPEC file against API shark of CloudVector"
authors = ["Bala Kumaran <balak@cloudvector.com>"]
# New attributes
license = "MIT"
readme = "README.md"
#homepage = "https://github.com/ArecaBay"
#repository = "https://github.com/ArecaBay"
keywords = ["cvapianalyser", "cloudvector", "apianalyser"]
classifiers = [
    "Environment :: Console",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Documentation",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Quality Assurance",
]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.2"
requests = "2.22.0"
jinja2 = "*"
pyyaml = "*"
cvapianalyser = "*"

[tool.poetry.dev-dependencies]
pex = "*"

[tool.poetry.scripts]
cvapianalyser = 'cvapianalyser.CVApiAnalyser:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
