[tool.poetry]
name = "WorldCoinAPI"
version = "1.0.2"
description = "API for WorldCoin (https://vk.com/app7614516)"
authors = ["Timtaran"]

[tool.poetry.dependencies]
python = "^3.5"
requests = "^2.24.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
