[tool.poetry]
name = "dtk_api"
version = "0.1.6"
description = "大淘客接口"
authors = ["dev <dev@qiyutech.tech>"]
readme = "README.md"

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple"
default = true

[tool.poetry.dependencies]
python = "^3.8"

pydantic = ">=1.6,<1.7"
requests = ">=2.24,<2.25"
aiohttp = ">=3.6,<3.7"

[tool.poetry.dev-dependencies]
black = ">=20.8b1"
pytest = ">=6.1,<6.2"
pytest-asyncio = ">=0.14"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
